Repository PGMDev/PGM, pull requests merged in 2020-11, with the labels that each got.

#701 Reintroduce drop-filter for flags
  core/src/main/java/tc/oc/pgm/filters/query/PlayerQuery.java
  core/src/main/java/tc/oc/pgm/flag/Flag.java
  core/src/main/java/tc/oc/pgm/flag/FlagDefinition.java
  core/src/main/java/tc/oc/pgm/flag/FlagParser.java
  core/src/main/java/tc/oc/pgm/flag/state/Carried.java
Labels: reintroduce

#718 Revert "Re-introduce filtered respawn options"
  core/src/main/java/tc/oc/pgm/spawns/RespawnOptions.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnMatchModule.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnModule.java
  core/src/main/java/tc/oc/pgm/spawns/states/State.java
Labels: urgent

#725 Add owner-points module
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPoint.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointDefinition.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
Labels: feature, reintroduce
