Repository PGMDev/PGM, pull requests merged in 2020-10, with the labels that each got.

#669 Fix spawnkits being ignored if no item has a slot
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
Labels: bug

#680 Prevent invalid tablist on vanish with forced teams
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
Labels: bug

#683 Resolve issues related to FFA timelimit & /match command
  core/src/main/java/tc/oc/pgm/score/ScoreMatchModule.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitModule.java
Labels: bug, urgent

#681 Cleanup player components & name decorations
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/namedecorations/ConfigDecorationProvider.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationProvider.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistry.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistryImpl.java
  util/src/main/java/tc/oc/pgm/util/named/NameDecorationProvider.java
  util/src/main/java/tc/oc/pgm/util/named/NameStyle.java
  util/src/main/java/tc/oc/pgm/util/text/types/PlayerComponent.java
Labels: refactor
