Repository PGMDev/PGM, pull requests merged in 2020-12, with the labels that each got.

#736 Fix several issues on player states
  core/src/main/java/tc/oc/pgm/api/player/MatchPlayer.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/spawns/states/Alive.java
  core/src/main/java/tc/oc/pgm/spawns/states/Dead.java
  core/src/main/java/tc/oc/pgm/spawns/states/Observing.java
  core/src/main/java/tc/oc/pgm/spawns/states/Spawning.java
  core/src/main/java/tc/oc/pgm/spawns/states/State.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: bug

#737 Dynamic tablist update delay
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
Labels: feature

#739 Make player death animation hitbox tiny
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnModule.java
  core/src/main/java/tc/oc/pgm/spawns/states/Dead.java
  core/src/main/resources/config.yml
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: feature

#744 Implement filters in blitz
  core/src/main/java/tc/oc/pgm/blitz/BlitzConfig.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzModule.java
Labels: feature

#745 Assign team columns proportional to team size in tab
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
Labels: feature

#746 Fix rounding issues on tab dynamic columns
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
Labels: bug

#760 Fix scoreboards breaking on long lines
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
Labels: bug, urgent

#761 Fix cycle bossbar not going after cycle
  core/src/main/java/tc/oc/pgm/countdowns/MatchCountdown.java
  core/src/main/java/tc/oc/pgm/cycle/CycleMatchModule.java
Labels: bug, urgent

#763 Prevent scoreboard rendering bugs on ffa
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
Labels: bug, urgent

#766 Fix several bossbar issues
  core/src/main/java/tc/oc/pgm/countdowns/MatchCountdown.java
  core/src/main/java/tc/oc/pgm/restart/RestartCountdown.java
  core/src/main/java/tc/oc/pgm/start/StartMatchModule.java
  core/src/main/java/tc/oc/pgm/timelimit/OvertimeCountdown.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitCountdown.java
Labels: bug, urgent

#751 Add query modifier for checking acting player info
  core/src/main/java/tc/oc/pgm/filters/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/modifier/PlayerBlockQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/modifier/QueryModifier.java
Labels: feature

#762 Implement filters on respawns & allow multiple of them
  core/src/main/java/tc/oc/pgm/spawns/RespawnOptions.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnMatchModule.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnModule.java
  core/src/main/java/tc/oc/pgm/spawns/states/State.java
Labels: feature
