Repository PGMDev/PGM, pull requests merged in 2020-05, with the labels that each got.

#439 [DOCS] Rework paragraph
  src/pages/index.js
Labels: docs

#432 Add spawner module
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/spawner/Spawnable.java
  core/src/main/java/tc/oc/pgm/spawner/Spawner.java
  core/src/main/java/tc/oc/pgm/spawner/SpawnerDefinition.java
  core/src/main/java/tc/oc/pgm/spawner/SpawnerMatchModule.java
  core/src/main/java/tc/oc/pgm/spawner/SpawnerModule.java
  core/src/main/java/tc/oc/pgm/spawner/objects/SpawnableItem.java
Labels: feature

#470 Add spawner module documentation
  docs/modules/mechanics/spawners.mdx
  sidebars.js
Labels: docs

#462 Vanish Improvements
  core/src/main/java/tc/oc/pgm/community/features/VanishManagerImpl.java
  util/src/main/i18n/templates/moderation.properties
Labels: bug

#494 Fix vehicle exiting not being filtered
  core/src/main/java/tc/oc/pgm/listeners/GeneralizingListener.java
Labels: bug, urgent

#504 Fix a vanished broadcast bug
  core/src/main/java/tc/oc/pgm/community/features/VanishManagerImpl.java
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
Labels: bug
