Repository PGMDev/PGM, pull requests merged in 2020-09, with the labels that each got.

#636 Remove legacy tablist and use modern tablist across versions
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/tablist/AuthorTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/LegacyMatchTabDisplay.java
  core/src/main/java/tc/oc/pgm/tablist/MapTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/MatchFooterTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
  util/src/main/i18n/templates/misc.properties
  util/src/main/java/tc/oc/pgm/util/tablist/TabDisplay.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: feature, refactor

#638 Fix tab display being setup previous to ignoring injection
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: bug, urgent

#637 Add flair hover to join/leave broadcast
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
Labels: feature

#639 Fix minor layour issues on legacy client tab
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: bug

#641 Fix NPE from recent picker changes
  core/src/main/java/tc/oc/pgm/picker/PickerMatchModule.java
Labels: bug

#645 Implement participating and observing filters
  core/src/main/java/tc/oc/pgm/filters/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/ParticipatingFilter.java
Labels: feature, reintroduce

#646 Support modifybowprojectile in 1.4 protocol
  core/src/main/java/tc/oc/pgm/modules/ModifyBowProjectileModule.java
Labels: bug, reintroduce

#654 Fix control points with names not being named
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
Labels: bug, urgent

#656 Fix spawners not spawning items randomly
  core/src/main/java/tc/oc/pgm/spawner/Spawner.java
Labels: bug, urgent

#655 Fix alt account broadcast issues
  core/src/main/java/tc/oc/pgm/community/command/ModerationCommand.java
Labels: bug

#660 Fix combat log tracker not detecting dead players properly
  core/src/main/java/tc/oc/pgm/tracker/trackers/CombatLogTracker.java
Labels: bug, urgent
