Repository PGMDev/PGM, pull requests merged in 2020-08, with the labels that each got.

#579 Prevent empty repo from cloning default maps
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/resources/config.yml
Labels: bug

#581 Add leak completion to cores
  core/src/main/java/tc/oc/pgm/core/Core.java
  core/src/main/java/tc/oc/pgm/core/CoreFactory.java
  core/src/main/java/tc/oc/pgm/core/CoreMatchModule.java
  core/src/main/java/tc/oc/pgm/core/CoreModule.java
  util/src/main/java/tc/oc/pgm/util/LegacyFormatUtils.java
Labels: feature

#582 Restore /recycle and /cycle [map]
  core/src/main/java/tc/oc/pgm/command/CycleCommand.java
Labels: bug

#588 Mitigate client autocompletion being flooded by tab entries
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
  util/src/main/java/tc/oc/pgm/util/tablist/SimpleTabEntry.java
Labels: bug

#586 Sort teams in sidebar for obs
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
Labels: bug, reintroduce

#587 Start reworking bossbars
  core/src/main/java/tc/oc/pgm/bossbar/BossBarMatchModule.java
  core/src/main/java/tc/oc/pgm/countdowns/MatchCountdown.java
  core/src/main/java/tc/oc/pgm/goals/Goal.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BlankBossBar.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBar.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBarObserver.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBarSource.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBarStack.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBarViaView.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBarView.java
  util/src/main/java/tc/oc/pgm/util/bossbar/BossBarWitherView.java
  util/src/main/java/tc/oc/pgm/util/bossbar/DynamicBossBar.java
  util/src/main/java/tc/oc/pgm/util/bossbar/StaticBossBar.java
  util/src/main/java/tc/oc/pgm/util/bukkit/ViaUtils.java
Labels: refactor

#591 Prevent match scheduler being used when match is unloaded
  core/src/main/java/tc/oc/pgm/tablist/MatchFooterTabEntry.java
Labels: bug, urgent

#595 Legacy fly after respawn fix
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
Labels: bug

#593 Prevent proximity metric none showing on scoreboard
  core/src/main/java/tc/oc/pgm/core/CoreFactory.java
  core/src/main/java/tc/oc/pgm/flag/Flag.java
  core/src/main/java/tc/oc/pgm/flag/FlagDefinition.java
  core/src/main/java/tc/oc/pgm/goals/ProximityGoalDefinition.java
  core/src/main/java/tc/oc/pgm/goals/ProximityMetric.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
  core/src/main/java/tc/oc/pgm/wool/MonumentWoolFactory.java
Labels: bug

#580 Allow customization of tablist footer
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/tablist/MatchFooterTabEntry.java
  core/src/main/resources/config.yml
Labels: feature, reintroduce

#597 Fix several tablist issues
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/tablist/LegacyMatchTabDisplay.java
  core/src/main/java/tc/oc/pgm/tablist/MatchFooterTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  pom.xml
  util/src/main/java/tc/oc/pgm/util/bukkit/ViaUtils.java
Labels: bug, urgent

#594 Update legacy flag beams with proposed changes from #550
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/flag/Flag.java
  core/src/main/java/tc/oc/pgm/flag/LegacyFlagBeamMatchModule.java
  core/src/main/java/tc/oc/pgm/flag/state/Carried.java
  core/src/main/resources/config.yml
  util/src/main/java/tc/oc/pgm/util/inventory/ItemBuilder.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: feature

#599 Improve tablist perf: cache header/foot & avoid ping
  core/src/main/java/tc/oc/pgm/tablist/LegacyMatchTabDisplay.java
  core/src/main/java/tc/oc/pgm/tablist/MatchFooterTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  util/src/main/java/tc/oc/pgm/util/tablist/DynamicTabEntry.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabDisplay.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabRender.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: bug, feature, urgent

#602 Further tablist performance improvements & fixes
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
  util/src/main/java/tc/oc/pgm/util/tablist/DynamicTabEntry.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabDisplay.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabManager.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: bug

#600 Send vote book content in chat for legacy players
  core/src/main/java/tc/oc/pgm/rotation/MapPoll.java
Labels: feature

#604 Allow tab to be extended & fix cycle white names
  core/src/main/java/tc/oc/pgm/match/MatchFactoryImpl.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistry.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistryImpl.java
  core/src/main/java/tc/oc/pgm/tablist/FreeForAllTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/LegacyMatchTabDisplay.java
  core/src/main/java/tc/oc/pgm/tablist/MapTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/MatchFooterTabEntry.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  core/src/main/java/tc/oc/pgm/tablist/TeamTabEntry.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
  util/src/main/java/tc/oc/pgm/util/tablist/PlayerTabEntry.java
  util/src/main/java/tc/oc/pgm/util/tablist/StaticTabEntry.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabEntry.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabRender.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
  util/src/main/java/tc/oc/pgm/util/text/types/PlayerComponent.java
Labels: bug, feature

#607 Prevent vanished players sometimes showing in tab after cycle
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
Labels: bug, urgent

#601 Add mercy option to score module
  core/src/main/java/tc/oc/pgm/score/MercyRule.java
  core/src/main/java/tc/oc/pgm/score/ScoreConfig.java
  core/src/main/java/tc/oc/pgm/score/ScoreMatchModule.java
  core/src/main/java/tc/oc/pgm/score/ScoreModule.java
Labels: feature

#620 Allow blockdrop trample on survival mode
  core/src/main/java/tc/oc/pgm/api/event/AdventureModeInteractEvent.java
  core/src/main/java/tc/oc/pgm/api/event/BlockTrampleEvent.java
  core/src/main/java/tc/oc/pgm/listeners/GeneralizingListener.java
Labels: bug, feature, reintroduce

#618 Send TNT alert in admin chat
  core/src/main/java/tc/oc/pgm/listeners/AntiGriefListener.java
  util/src/main/i18n/templates/moderation.properties
Labels: feature, reintroduce

#611 Implement overtime
  core/src/main/java/tc/oc/pgm/api/match/Match.java
  core/src/main/java/tc/oc/pgm/command/TimeLimitCommand.java
  core/src/main/java/tc/oc/pgm/command/graph/CommandGraph.java
  core/src/main/java/tc/oc/pgm/command/graph/VictoryConditionProvider.java
  core/src/main/java/tc/oc/pgm/countdowns/CountdownContext.java
  core/src/main/java/tc/oc/pgm/countdowns/CountdownRunner.java
  core/src/main/java/tc/oc/pgm/countdowns/SingleCountdownContext.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/result/VictoryConditions.java
  core/src/main/java/tc/oc/pgm/timelimit/OvertimeCountdown.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimit.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitCountdown.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitMatchModule.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitModule.java
  util/src/main/i18n/templates/match.properties
  util/src/main/i18n/templates/misc.properties
Labels: feature, refactor

#616 Fix mercy rules when leader scores 0 points
  core/src/main/java/tc/oc/pgm/score/MercyRule.java
Labels: bug

#606 Prevent team griefing on scored matches
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/score/ScoreMatchModule.java
  core/src/main/resources/config.yml
  util/src/main/i18n/templates/join.properties
Labels: feature

#608 Add group hover info to chat
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  core/src/main/java/tc/oc/pgm/namedecorations/ConfigDecorationProvider.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationProvider.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistry.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistryImpl.java
  core/src/main/resources/config.yml
  util/src/main/i18n/templates/misc.properties
  util/src/main/java/tc/oc/pgm/util/text/TextFormatter.java
  util/src/main/java/tc/oc/pgm/util/text/types/PlayerComponent.java
Labels: bug, feature

#617 Add map created date
  core/src/main/java/tc/oc/pgm/api/map/MapInfo.java
  core/src/main/java/tc/oc/pgm/command/MapCommand.java
  core/src/main/java/tc/oc/pgm/map/MapInfoImpl.java
  util/src/main/i18n/templates/map.properties
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature

#632 Implement rendering arbitrary team amounts on tablist
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
Labels: feature, refactor
