Repository PGMDev/PGM, pull requests merged in 2021-02, with the labels that each got.

#799 Reintroduce team switch kit
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/command/TeamCommand.java
  core/src/main/java/tc/oc/pgm/kits/DelayedKit.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/kits/TeamSwitchKit.java
  core/src/main/java/tc/oc/pgm/teams/TeamMatchModule.java
Labels: reintroduce

#806 Fix freeze title duration NPE
  core/src/main/java/tc/oc/pgm/community/modules/FreezeMatchModule.java
Labels: bug

#805 Rework stats and allow showing own stats
  .gitignore
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/api/match/event/MatchStatsEvent.java
  core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
  core/src/main/resources/config.yml
  util/src/main/i18n/templates/match.properties
Labels: feature

#814 Fix errors when no mappool exists
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java
Labels: bug, urgent

#815 Find match player even if entity is in wrong world
  core/src/main/java/tc/oc/pgm/match/MatchManagerImpl.java
Labels: bug

#816 Fix match end stats showing current killstreak instead of max
  core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
Labels: bug

#823 Add grounded filter
  core/src/main/java/tc/oc/pgm/filters/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/GroundedFilter.java
Labels: feature, reintroduce
