Repository PGMDev/PGM, pull requests merged in 2021-11, with the labels that each got.

#934 Throttle tablist based on tps & match cycle
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  util/src/main/java/tc/oc/pgm/util/bukkit/ViaUtils.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: feature, ready

#933 Apply item mods to across modules
  core/src/main/java/tc/oc/pgm/blockdrops/BlockDropsModule.java
  core/src/main/java/tc/oc/pgm/itemmeta/ItemModifyMatchModule.java
  core/src/main/java/tc/oc/pgm/killreward/KillRewardModule.java
  core/src/main/java/tc/oc/pgm/modules/ToolRepairMatchModule.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: bug, ready

#932 Add dynamic kit rules
  core/src/main/java/tc/oc/pgm/kits/KitMatchModule.java
  core/src/main/java/tc/oc/pgm/kits/KitModule.java
  core/src/main/java/tc/oc/pgm/kits/KitRule.java
Labels: feature, ready

#931 Add infinite attribute to blocks
  core/src/main/java/tc/oc/pgm/kits/KitMatchModule.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/kits/tag/ItemTags.java
Labels: ready

#926 Add Filters to Monument Modes
  core/src/main/java/tc/oc/pgm/command/ModeCommand.java
  core/src/main/java/tc/oc/pgm/modes/Mode.java
  core/src/main/java/tc/oc/pgm/modes/ModesPaginatedResult.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesMatchModule.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesModule.java
  util/src/main/i18n/templates/command.properties
Labels: feature, hacktoberfest-accepted, ready

#910 annotate TNTRenderMatchModule with ListenerScope
  core/src/main/java/tc/oc/pgm/tntrender/TNTRenderMatchModule.java
Labels: ready

#840 Better spectate
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/api/player/MatchPlayer.java
  core/src/main/java/tc/oc/pgm/death/DeathMessageMatchModule.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/modules/SpectateMatchModule.java
  core/src/main/java/tc/oc/pgm/spawns/states/Dead.java
  core/src/main/java/tc/oc/pgm/spawns/states/Joining.java
  core/src/main/java/tc/oc/pgm/spawns/states/Spawning.java
  util/src/main/i18n/templates/death.properties
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: feature, ready

#936 Fix missing death messages
  core/src/main/java/tc/oc/pgm/api/player/event/MatchPlayerDeathEvent.java
Labels: bug, urgent

#944 Fix early hits stealing fall kills
  core/src/main/java/tc/oc/pgm/tracker/info/FallState.java
  core/src/main/java/tc/oc/pgm/tracker/trackers/FallTracker.java
Labels: bug
