Repository PGMDev/PGM, pull requests merged in 2021-03, with the labels that each got.

#826 Fix inventory npe
  util/src/main/java/tc/oc/pgm/util/menu/InventoryMenu.java
Labels: bug, urgent

#825 Make completion sounds for control points half as loud
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPoint.java
  core/src/main/java/tc/oc/pgm/goals/Goal.java
  core/src/main/java/tc/oc/pgm/goals/GoalMatchModule.java
  core/src/main/java/tc/oc/pgm/goals/SimpleGoal.java
Labels: feature

#827 Fix error caused by maps not using <world>
  core/src/main/java/tc/oc/pgm/modules/WorldTimeModule.java
Labels: bug, urgent

#828 Update adventure to 4.7.0
  pom.xml
Labels: urgent

#830 Avoid faulty initialization of wool proximity
  core/src/main/java/tc/oc/pgm/wool/MonumentWool.java
Labels: bug

#829 Make victory conditions respect completion rules
  core/src/main/java/tc/oc/pgm/api/match/Match.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
  core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
Labels: feature, reintroduce

#832 Implement end overtime
  core/src/main/java/tc/oc/pgm/command/TimeLimitCommand.java
  core/src/main/java/tc/oc/pgm/timelimit/OvertimeCountdown.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimit.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitModule.java
Labels: feature
