Repository PGMDev/PGM, pull requests merged in 2021-04, with the labels that each got.

#843 Fix DoubleRowMenuArranger
  util/src/main/java/tc/oc/pgm/util/menu/pattern/DoubleRowMenuArranger.java
Labels: bug

#841 Fix KitModule dependencies
  core/src/main/java/tc/oc/pgm/kits/KitModule.java
Labels: bug

#842 Fix several issues with flag beams
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/flag/Flag.java
  core/src/main/java/tc/oc/pgm/flag/LegacyFlagBeamMatchModule.java
  core/src/main/java/tc/oc/pgm/flag/state/Carried.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: bug

#845 Fix match start message being shown on finished matches
  core/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java
Labels: bug

#847 Track burning kills from being punched into lava
  core/src/main/java/tc/oc/pgm/tracker/info/FallState.java
  core/src/main/java/tc/oc/pgm/tracker/trackers/FallTracker.java
Labels: bug

#848 Rewrite legacy flag beams
  core/src/main/java/tc/oc/pgm/flag/LegacyFlagBeamMatchModule.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
Labels: bug

#849 Fix flag beams dying in the void
  core/src/main/java/tc/oc/pgm/flag/LegacyFlagBeamMatchModule.java
Labels: bug, urgent

#861 Fix ItemTag meta not being set
  util/src/main/java/tc/oc/pgm/util/inventory/tag/LegacyItemTag.java
Labels: urgent
