Repository PGMDev/PGM, pull requests merged in 2021-01, with the labels that each got.

#773 Add a length check to sidebar title
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
Labels: bug

#775 Cleanup map pool manager & fix blitz obs count
  core/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java
Labels: bug

#785 Fix invalid state when quitting from incorrect world
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
Labels: bug

#729 Menu fixes and refactors
  core/src/main/java/tc/oc/pgm/command/StatsCommand.java
  core/src/main/java/tc/oc/pgm/menu/InventoryMenu.java
  core/src/main/java/tc/oc/pgm/menu/InventoryMenuItem.java
  core/src/main/java/tc/oc/pgm/menu/InventoryMenuUtils.java
  core/src/main/java/tc/oc/pgm/menu/PageInventoryMenuItem.java
  core/src/main/java/tc/oc/pgm/observers/ObserverToolsInventoryMenuItem.java
  core/src/main/java/tc/oc/pgm/observers/ObserverToolsMatchModule.java
  core/src/main/java/tc/oc/pgm/observers/tools/FlySpeedTool.java
  core/src/main/java/tc/oc/pgm/observers/tools/GamemodeTool.java
  core/src/main/java/tc/oc/pgm/observers/tools/NightVisionTool.java
  core/src/main/java/tc/oc/pgm/observers/tools/VisibilityTool.java
  core/src/main/java/tc/oc/pgm/stats/PlayerStats.java
  core/src/main/java/tc/oc/pgm/stats/PlayerStatsInventoryMenuItem.java
  core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
  core/src/main/java/tc/oc/pgm/stats/TeamStatsInventoryMenuItem.java
  core/src/main/java/tc/oc/pgm/stats/VerboseStatsInventoryMenuItem.java
  util/src/main/java/tc/oc/pgm/util/menu/InventoryMenu.java
  util/src/main/java/tc/oc/pgm/util/menu/InventoryMenuItem.java
  util/src/main/java/tc/oc/pgm/util/menu/InventoryMenuUtils.java
  util/src/main/java/tc/oc/pgm/util/menu/pattern/DoubleRowMenuArranger.java
  util/src/main/java/tc/oc/pgm/util/menu/pattern/IdentityMenuArranger.java
  util/src/main/java/tc/oc/pgm/util/menu/pattern/MenuArranger.java
  util/src/main/java/tc/oc/pgm/util/menu/pattern/SingleRowMenuArranger.java
Labels: bug

#758 Add Selectable Monument Modes
  core/src/main/java/tc/oc/pgm/core/Core.java
  core/src/main/java/tc/oc/pgm/core/CoreFactory.java
  core/src/main/java/tc/oc/pgm/core/CoreMatchModule.java
  core/src/main/java/tc/oc/pgm/core/CoreModule.java
  core/src/main/java/tc/oc/pgm/destroyable/Destroyable.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableFactory.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableMatchModule.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableModule.java
  core/src/main/java/tc/oc/pgm/goals/ModeChangeGoal.java
  core/src/main/java/tc/oc/pgm/modes/Mode.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesModule.java
Labels: feature

#786 Fix timelimit victory condition being ignored after match end
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimit.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitCountdown.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitMatchModule.java
Labels: bug

#789 Fix obs bias on blitz for mappools
  core/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java
Labels: bug, urgent
