Repository PGMDev/PGM, pull requests merged in 2021-07, with the labels that each got.

#893 Fallback map order fix
  core/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java
Labels: bug

#897 Round longest player shot stat not ceil
  core/src/main/java/tc/oc/pgm/stats/PlayerStats.java
Labels: bug

#896 Add debug message when map XML reloaded
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
Labels: feature

#873 Add <gamemode> module
  core/src/main/java/tc/oc/pgm/api/map/Gamemode.java
  core/src/main/java/tc/oc/pgm/api/map/MapInfo.java
  core/src/main/java/tc/oc/pgm/map/MapInfoImpl.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
  util/src/main/i18n/templates/gamemode.properties
Labels: feature

#903 Allow gamemode to be case insensitive
  core/src/main/java/tc/oc/pgm/api/map/Gamemode.java
Labels: bug, urgent
