Repository PGMDev/PGM, pull requests merged in 2022-10, with the labels that each got.

#1061 Add item replace action
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/ReplaceItemAction.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
  core/src/main/java/tc/oc/pgm/filters/operator/AllFilter.java
  core/src/main/java/tc/oc/pgm/filters/operator/AnyFilter.java
  core/src/main/java/tc/oc/pgm/filters/operator/OneFilter.java
  core/src/main/java/tc/oc/pgm/killreward/KillRewardMatchModule.java
  core/src/main/java/tc/oc/pgm/kits/ArmorKit.java
  core/src/main/java/tc/oc/pgm/kits/ItemKit.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/kits/tag/ItemModifier.java
  core/src/main/java/tc/oc/pgm/shops/menu/ShopMenu.java
Labels: feature

#1065 Fix fireworks on non-finite regions crashing the server
  core/src/main/java/tc/oc/pgm/fireworks/FireworkMatchModule.java
Labels: bug, urgent

#1066 Implement dye color option for teams
  core/src/main/java/tc/oc/pgm/api/party/Party.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointBlockDisplay.java
  core/src/main/java/tc/oc/pgm/ffa/Tribute.java
  core/src/main/java/tc/oc/pgm/goals/OwnedGoal.java
  core/src/main/java/tc/oc/pgm/kits/tag/ItemModifier.java
  core/src/main/java/tc/oc/pgm/match/ObserverParty.java
  core/src/main/java/tc/oc/pgm/match/PartyImpl.java
  core/src/main/java/tc/oc/pgm/match/QueuedParty.java
  core/src/main/java/tc/oc/pgm/payload/Payload.java
  core/src/main/java/tc/oc/pgm/teams/Team.java
  core/src/main/java/tc/oc/pgm/teams/TeamFactory.java
  core/src/main/java/tc/oc/pgm/teams/TeamModule.java
Labels: feature

#1069 Implement blitz join filter
  core/src/main/java/tc/oc/pgm/blitz/BlitzConfig.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzModule.java
  core/src/main/java/tc/oc/pgm/picker/PickerMatchModule.java
Labels: feature

#1067 Implement title and actionbar for message action
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/ChatMessageAction.java
  core/src/main/java/tc/oc/pgm/action/actions/MessageAction.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature

#1076 Implement blocks filter & refactor regions
  core/src/main/java/tc/oc/pgm/api/region/Region.java
  core/src/main/java/tc/oc/pgm/blockdrops/BlockDropsRuleSet.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointBlockDisplay.java
  core/src/main/java/tc/oc/pgm/core/Core.java
  core/src/main/java/tc/oc/pgm/destroyable/Destroyable.java
  core/src/main/java/tc/oc/pgm/filters/matcher/block/BlocksFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/block/MaterialFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/payload/PayloadRegion.java
  core/src/main/java/tc/oc/pgm/regions/AbstractRegion.java
  core/src/main/java/tc/oc/pgm/regions/BlockRegion.java
  core/src/main/java/tc/oc/pgm/regions/CircleRegion.java
  core/src/main/java/tc/oc/pgm/regions/Complement.java
  core/src/main/java/tc/oc/pgm/regions/CuboidRegion.java
  core/src/main/java/tc/oc/pgm/regions/CylindricalRegion.java
  core/src/main/java/tc/oc/pgm/regions/EmptyRegion.java
  core/src/main/java/tc/oc/pgm/regions/EverywhereRegion.java
  core/src/main/java/tc/oc/pgm/regions/FiniteBlockRegion.java
  core/src/main/java/tc/oc/pgm/regions/HalfspaceRegion.java
  core/src/main/java/tc/oc/pgm/regions/Intersect.java
  core/src/main/java/tc/oc/pgm/regions/NegativeRegion.java
  core/src/main/java/tc/oc/pgm/regions/PointRegion.java
  core/src/main/java/tc/oc/pgm/regions/RectangleRegion.java
  core/src/main/java/tc/oc/pgm/regions/SectorRegion.java
  core/src/main/java/tc/oc/pgm/regions/SphereRegion.java
  core/src/main/java/tc/oc/pgm/regions/TransformedRegion.java
  core/src/main/java/tc/oc/pgm/regions/Union.java
  core/src/main/java/tc/oc/pgm/regions/XMLRegionReference.java
  util/src/main/java/tc/oc/pgm/util/block/BlockVectorSet.java
  util/src/main/java/tc/oc/pgm/util/block/BlockVectors.java
  util/src/main/java/tc/oc/pgm/util/xml/Node.java
Labels: feature

#1074 Allow triggers to support child definitions
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
Labels: feature

#1078 Fix monostable filter scope forward reference
  core/src/main/java/tc/oc/pgm/api/filter/query/MatchQuery.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/MonostableFilter.java
Labels: bug

#1043 Add filters for dead and alive states
  core/src/main/java/tc/oc/pgm/filters/matcher/player/PlayerStateFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
Labels: feature

#1079 Fix missing dependency on shop module
  core/src/main/java/tc/oc/pgm/shops/ShopModule.java
Labels: urgent

#1045 EnderChest support 👻
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/enderchest/Dropoff.java
  core/src/main/java/tc/oc/pgm/enderchest/DropoffFallback.java
  core/src/main/java/tc/oc/pgm/enderchest/EnderChestMatchModule.java
  core/src/main/java/tc/oc/pgm/enderchest/EnderChestModule.java
Labels: feature

#1088 Fix being unable to set chat channels
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
Labels: bug
