Repository PGMDev/PGM, pull requests merged in 2022-11, with the labels that each got.

#1087 Add random function to formulas
  util/src/main/java/tc/oc/pgm/util/math/Formula.java
Labels: feature, ready

#1046 Score Minimum Value
  core/src/main/java/tc/oc/pgm/score/MercyRule.java
  core/src/main/java/tc/oc/pgm/score/ScoreConfig.java
  core/src/main/java/tc/oc/pgm/score/ScoreMatchModule.java
  core/src/main/java/tc/oc/pgm/score/ScoreModule.java
Labels: feature, ready

#1029 Structures
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/api/module/ModuleGraph.java
  core/src/main/java/tc/oc/pgm/api/region/Region.java
  core/src/main/java/tc/oc/pgm/filters/matcher/StaticFilter.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/renewable/RenewableModule.java
  core/src/main/java/tc/oc/pgm/snapshot/BudgetWorldEdit.java
  core/src/main/java/tc/oc/pgm/snapshot/SnapshotMatchModule.java
  core/src/main/java/tc/oc/pgm/structure/DynamicStructure.java
  core/src/main/java/tc/oc/pgm/structure/DynamicStructureDefinition.java
  core/src/main/java/tc/oc/pgm/structure/StructureDefinition.java
  core/src/main/java/tc/oc/pgm/structure/StructureMatchModule.java
  core/src/main/java/tc/oc/pgm/structure/StructureModule.java
  core/src/main/java/tc/oc/pgm/util/BlockData.java
  util/src/main/java/tc/oc/pgm/util/chunk/ChunkVector.java
Labels: feature, reintroduce, ready

#1092 Fix unsafe substring calls
  core/src/main/java/tc/oc/pgm/inventory/ViewInventoryMatchModule.java
  util/src/main/java/tc/oc/pgm/util/StringUtils.java
Labels: bug, urgent

#1093 Fix NPE with new mercy min attribute
  core/src/main/java/tc/oc/pgm/score/ScoreModule.java
Labels: bug, urgent

#1097 Fix shading of cloud's libs
  core/pom.xml
  pom.xml
Labels: bug, urgent

#1082 Parse Blitz: Rage Gamemode Automatically
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
Labels: feature

#1100 Fixup & rework many issues introduced by cloud
  core/src/main/java/tc/oc/pgm/api/setting/SettingKey.java
  core/src/main/java/tc/oc/pgm/command/AdminCommand.java
  core/src/main/java/tc/oc/pgm/command/ClassCommand.java
  core/src/main/java/tc/oc/pgm/command/FreeForAllCommand.java
  core/src/main/java/tc/oc/pgm/command/InventoryCommand.java
  core/src/main/java/tc/oc/pgm/command/JoinCommand.java
  core/src/main/java/tc/oc/pgm/command/MapCommand.java
  core/src/main/java/tc/oc/pgm/command/MapDevCommand.java
  core/src/main/java/tc/oc/pgm/command/MapPoolCommand.java
  core/src/main/java/tc/oc/pgm/command/ModeCommand.java
  core/src/main/java/tc/oc/pgm/command/ProximityCommand.java
  core/src/main/java/tc/oc/pgm/command/SettingCommand.java
  core/src/main/java/tc/oc/pgm/command/StartCommand.java
  core/src/main/java/tc/oc/pgm/command/StatsCommand.java
  core/src/main/java/tc/oc/pgm/command/TeamCommand.java
  core/src/main/java/tc/oc/pgm/command/TimeLimitCommand.java
  core/src/main/java/tc/oc/pgm/command/injectors/MapPollProvider.java
  core/src/main/java/tc/oc/pgm/command/injectors/MapPoolManagerProvider.java
  core/src/main/java/tc/oc/pgm/command/injectors/MatchModuleInjectionService.java
  core/src/main/java/tc/oc/pgm/command/injectors/MatchObjectProvider.java
  core/src/main/java/tc/oc/pgm/command/injectors/MatchProvider.java
  core/src/main/java/tc/oc/pgm/command/injectors/TeamMatchModuleProvider.java
  core/src/main/java/tc/oc/pgm/command/injectors/TeamModuleInjector.java
  core/src/main/java/tc/oc/pgm/command/parsers/EnumParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/MapInfoParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/MapPoolParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/MatchObjectParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/MatchPlayerParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/ModeParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/PartyParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/PlayerClassParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/RotationParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/SettingKeyParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/SettingValueParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/TeamParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/TeamsParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/VictoryConditionParser.java
  core/src/main/java/tc/oc/pgm/command/util/CommandGraph.java
  core/src/main/java/tc/oc/pgm/command/util/CommandKeys.java
  core/src/main/java/tc/oc/pgm/command/util/CommandUtils.java
  core/src/main/java/tc/oc/pgm/command/util/ParserConstants.java
  core/src/main/java/tc/oc/pgm/features/SelfIdentifyingFeatureDefinition.java
  core/src/main/java/tc/oc/pgm/modes/Mode.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesMatchModule.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesModule.java
  core/src/main/java/tc/oc/pgm/rotation/MapPoolManager.java
  core/src/main/java/tc/oc/pgm/rotation/pools/DisabledMapPool.java
  core/src/main/java/tc/oc/pgm/rotation/pools/MapPool.java
  core/src/main/java/tc/oc/pgm/rotation/pools/MapPoolType.java
  core/src/main/java/tc/oc/pgm/rotation/pools/RandomMapPool.java
  core/src/main/java/tc/oc/pgm/rotation/pools/Rotation.java
  core/src/main/java/tc/oc/pgm/rotation/pools/VotingPool.java
  core/src/main/java/tc/oc/pgm/util/Players.java
  core/src/main/java/tc/oc/pgm/util/PrettyPaginatedComponentResults.java
  pom.xml
  util/src/main/i18n/templates/command.properties
  util/src/main/i18n/templates/misc.properties
  util/src/main/java/tc/oc/pgm/util/Aliased.java
  util/src/main/java/tc/oc/pgm/util/StringUtils.java
  util/src/main/java/tc/oc/pgm/util/text/TextException.java
Labels: bug

#1104 Implement bossbars for cooldown filter
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/countdowns/MatchCountdown.java
  core/src/main/java/tc/oc/pgm/filters/Filterable.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/MonostableFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/flag/state/Respawning.java
  core/src/main/java/tc/oc/pgm/modes/ModesPaginatedResult.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileCooldown.java
  util/src/main/java/tc/oc/pgm/util/text/TemporalComponent.java
  util/src/test/java/tc/oc/pgm/util/text/TemporalComponentTest.java
Labels: reintroduce

#1109 Fix NPE on pgm reload due to text translation changes
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  util/src/main/java/tc/oc/pgm/util/text/TextTranslations.java
Labels: bug, urgent

#1107 Fix structure clear removing instead of restoring blocks
  core/src/main/java/tc/oc/pgm/snapshot/BudgetWorldEdit.java
  core/src/main/java/tc/oc/pgm/snapshot/SnapshotMatchModule.java
  core/src/main/java/tc/oc/pgm/snapshot/WorldSnapshot.java
  core/src/main/java/tc/oc/pgm/structure/DynamicStructure.java
  core/src/main/java/tc/oc/pgm/structure/Structure.java
  core/src/main/java/tc/oc/pgm/structure/StructureDefinition.java
  core/src/main/java/tc/oc/pgm/structure/StructureMatchModule.java
  core/src/main/java/tc/oc/pgm/structure/StructureModule.java
Labels: bug, reintroduce

#1108 Make module graph load order consistent
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/action/ActionModule.java
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/api/map/factory/MapFactory.java
  core/src/main/java/tc/oc/pgm/api/map/factory/MapModuleFactory.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzModule.java
  core/src/main/java/tc/oc/pgm/blockdrops/BlockDropsModule.java
  core/src/main/java/tc/oc/pgm/broadcast/BroadcastModule.java
  core/src/main/java/tc/oc/pgm/classes/ClassModule.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointModule.java
  core/src/main/java/tc/oc/pgm/core/CoreModule.java
  core/src/main/java/tc/oc/pgm/crafting/CraftingModule.java
  core/src/main/java/tc/oc/pgm/damage/DamageModule.java
  core/src/main/java/tc/oc/pgm/damage/DisableDamageModule.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableModule.java
  core/src/main/java/tc/oc/pgm/enderchest/EnderChestModule.java
  core/src/main/java/tc/oc/pgm/fallingblocks/FallingBlocksModule.java
  core/src/main/java/tc/oc/pgm/ffa/FreeForAllModule.java
  core/src/main/java/tc/oc/pgm/filters/FilterModule.java
  core/src/main/java/tc/oc/pgm/flag/FlagModule.java
  core/src/main/java/tc/oc/pgm/gamerules/GameRulesModule.java
  core/src/main/java/tc/oc/pgm/hunger/HungerModule.java
  core/src/main/java/tc/oc/pgm/killreward/KillRewardModule.java
  core/src/main/java/tc/oc/pgm/kits/KitModule.java
  core/src/main/java/tc/oc/pgm/map/MapContextImpl.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesModule.java
  core/src/main/java/tc/oc/pgm/modules/DiscardPotionBottlesModule.java
  core/src/main/java/tc/oc/pgm/modules/FriendlyFireRefundModule.java
  core/src/main/java/tc/oc/pgm/modules/InternalModule.java
  core/src/main/java/tc/oc/pgm/modules/ItemDestroyModule.java
  core/src/main/java/tc/oc/pgm/modules/ItemKeepModule.java
  core/src/main/java/tc/oc/pgm/modules/MobsModule.java
  core/src/main/java/tc/oc/pgm/modules/ModifyBowProjectileModule.java
  core/src/main/java/tc/oc/pgm/modules/ToolRepairModule.java
  core/src/main/java/tc/oc/pgm/modules/WorldTimeModule.java
  core/src/main/java/tc/oc/pgm/portals/PortalModule.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileModule.java
  core/src/main/java/tc/oc/pgm/proximity/ProximityAlarmModule.java
  core/src/main/java/tc/oc/pgm/rage/RageModule.java
  core/src/main/java/tc/oc/pgm/regions/RegionModule.java
  core/src/main/java/tc/oc/pgm/renewable/RenewableModule.java
  core/src/main/java/tc/oc/pgm/score/ScoreModule.java
  core/src/main/java/tc/oc/pgm/shops/ShopModule.java
  core/src/main/java/tc/oc/pgm/spawner/SpawnerModule.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnModule.java
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimitModule.java
  core/src/main/java/tc/oc/pgm/tnt/TNTModule.java
  core/src/main/java/tc/oc/pgm/wool/WoolModule.java
  core/src/main/java/tc/oc/pgm/worldborder/WorldBorderModule.java
Labels: refactor
