Repository PGMDev/PGM, pull requests merged in 2022-09, with the labels that each got.

#1052 Fix world border filter NPE
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/filters/FilterModule.java
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/LegacyFilterParser.java
  core/src/main/java/tc/oc/pgm/worldborder/WorldBorderModule.java
  util/src/main/java/tc/oc/pgm/util/collection/ContextStore.java
Labels: bug, urgent, ready

#1050 Fix objective filter not reacting dynamically
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/filters/operator/TeamFilterAdapter.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesMatchModule.java
Labels: bug, urgent, ready

#1049 Add options for item kits being given to players
  core/src/main/java/tc/oc/pgm/kits/ItemKit.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
Labels: feature, ready

#1048 Fix mode commands with filtered modes
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesMatchModule.java
Labels: bug, ready

#1028 Reintroduce include statements
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/api/map/MapLibrary.java
  core/src/main/java/tc/oc/pgm/api/map/MapSource.java
  core/src/main/java/tc/oc/pgm/api/map/includes/MapInclude.java
  core/src/main/java/tc/oc/pgm/api/map/includes/MapIncludeProcessor.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeImpl.java
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeProcessorImpl.java
  core/src/main/java/tc/oc/pgm/map/source/SystemMapSourceFactory.java
  core/src/main/resources/config.yml
Labels: feature, reintroduce, ready

#1053 Cleanup filter & region parsing & validation
  core/src/main/java/tc/oc/pgm/api/filter/Filter.java
  core/src/main/java/tc/oc/pgm/command/ModeCommand.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
  core/src/main/java/tc/oc/pgm/core/CoreModule.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableModule.java
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  core/src/main/java/tc/oc/pgm/filters/FilterDispatcher.java
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/filters/XMLFilterReference.java
  core/src/main/java/tc/oc/pgm/filters/operator/FilterNode.java
  core/src/main/java/tc/oc/pgm/filters/operator/MultiFilterFunction.java
  core/src/main/java/tc/oc/pgm/filters/operator/SingleFilterFunction.java
  core/src/main/java/tc/oc/pgm/filters/parse/DynamicFilterValidation.java
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/LegacyFilterParser.java
  core/src/main/java/tc/oc/pgm/flag/FlagParser.java
  core/src/main/java/tc/oc/pgm/kits/KitModule.java
  core/src/main/java/tc/oc/pgm/modes/Mode.java
  core/src/main/java/tc/oc/pgm/modes/ModesPaginatedResult.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesMatchModule.java
  core/src/main/java/tc/oc/pgm/modes/ObjectiveModesModule.java
  core/src/main/java/tc/oc/pgm/portals/PortalModule.java
  core/src/main/java/tc/oc/pgm/regions/FeatureRegionParser.java
  core/src/main/java/tc/oc/pgm/regions/LegacyRegionParser.java
  core/src/main/java/tc/oc/pgm/regions/RegionParser.java
  core/src/main/java/tc/oc/pgm/regions/XMLRegionReference.java
  core/src/main/java/tc/oc/pgm/renewable/RenewableModule.java
  core/src/main/java/tc/oc/pgm/util/PrettyPaginatedResult.java
  core/src/main/java/tc/oc/pgm/util/XMLParser.java
  util/src/main/i18n/templates/command.properties
  util/src/main/java/tc/oc/pgm/util/xml/Node.java
Labels: bug, ready

#1047 Implement variables!
  core/src/main/java/tc/oc/pgm/action/ActionModule.java
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/ActionNode.java
  core/src/main/java/tc/oc/pgm/action/actions/SetVariableAction.java
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/api/filter/Filterables.java
  core/src/main/java/tc/oc/pgm/command/MapDevCommand.java
  core/src/main/java/tc/oc/pgm/command/graph/CommandGraph.java
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  core/src/main/java/tc/oc/pgm/filters/FilterModule.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/MonostableFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/VariableFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/party/CompetitorFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/party/GoalFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/party/RankFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/party/ScoreFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/party/TeamVariableFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/variables/Variable.java
  core/src/main/java/tc/oc/pgm/variables/VariableContextBuilder.java
  core/src/main/java/tc/oc/pgm/variables/VariableDefinition.java
  core/src/main/java/tc/oc/pgm/variables/VariablesMatchModule.java
  core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
  util/src/main/java/tc/oc/pgm/util/math/Formula.java
Labels: feature, ready

#1030 Add kill-entities action
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/KillEntitiesAction.java
Labels: feature, ready

#1058 Fix unknown players on join
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
Labels: urgent

#1055 Implement item matchers
  core/src/main/java/tc/oc/pgm/api/module/exception/ModuleLoadException.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/CarryingItemFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/HoldingItemFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/ParticipantItemFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/WearingItemFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  util/src/main/java/tc/oc/pgm/util/inventory/ItemMatcher.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature

#1059 Implement payload (prototype)
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPoint.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointDefinition.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointMatchModule.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointModule.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
  core/src/main/java/tc/oc/pgm/controlpoint/RegionPlayerTracker.java
  core/src/main/java/tc/oc/pgm/fireworks/FireworkMatchModule.java
  core/src/main/java/tc/oc/pgm/match/MatchManagerImpl.java
  core/src/main/java/tc/oc/pgm/payload/Payload.java
  core/src/main/java/tc/oc/pgm/payload/PayloadDefinition.java
  core/src/main/java/tc/oc/pgm/payload/PayloadListener.java
  core/src/main/java/tc/oc/pgm/payload/PayloadRegion.java
  core/src/main/java/tc/oc/pgm/payload/track/BackwardsRail.java
  core/src/main/java/tc/oc/pgm/payload/track/CurvedRail.java
  core/src/main/java/tc/oc/pgm/payload/track/RailDirection.java
  core/src/main/java/tc/oc/pgm/payload/track/RailOffset.java
  core/src/main/java/tc/oc/pgm/payload/track/SlopedRail.java
  core/src/main/java/tc/oc/pgm/payload/track/StraightRail.java
  core/src/main/java/tc/oc/pgm/payload/track/Track.java
  core/src/main/resources/config.yml
Labels: feature, discussion

#1038 Interactive Shops 🛒
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/kits/AbstractKit.java
  core/src/main/java/tc/oc/pgm/kits/ItemKit.java
  core/src/main/java/tc/oc/pgm/kits/Kit.java
  core/src/main/java/tc/oc/pgm/kits/KitNode.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/kits/OverflowWarningKit.java
  core/src/main/java/tc/oc/pgm/kits/XMLKitReference.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/points/PointParser.java
  core/src/main/java/tc/oc/pgm/shops/Shop.java
  core/src/main/java/tc/oc/pgm/shops/ShopKeeper.java
  core/src/main/java/tc/oc/pgm/shops/ShopMatchModule.java
  core/src/main/java/tc/oc/pgm/shops/ShopModule.java
  core/src/main/java/tc/oc/pgm/shops/menu/Category.java
  core/src/main/java/tc/oc/pgm/shops/menu/Icon.java
  core/src/main/java/tc/oc/pgm/shops/menu/Payment.java
  core/src/main/java/tc/oc/pgm/shops/menu/ShopMenu.java
  util/src/main/i18n/templates/match.properties
  util/src/main/i18n/templates/ui.properties
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
  util/src/main/java/tc/oc/pgm/util/text/TextParser.java
Labels: feature, ready
