Repository PGMDev/PGM, pull requests merged in 2022-04, with the labels that each got.

#985 Prevent team balance broadcast when disabled
  core/src/main/java/tc/oc/pgm/start/StartCountdown.java
Labels: bug

#964 Refactor FeatureDefinitionContext to extend ContextStore
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  util/src/main/java/tc/oc/pgm/util/collection/ContextStore.java
Labels: ready

#984 Rewrite flag posts to support more configurations
  core/src/main/java/tc/oc/pgm/filters/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/FlagStateFilter.java
  core/src/main/java/tc/oc/pgm/filters/query/GoalQuery.java
  core/src/main/java/tc/oc/pgm/flag/Flag.java
  core/src/main/java/tc/oc/pgm/flag/FlagDefinition.java
  core/src/main/java/tc/oc/pgm/flag/FlagMatchModule.java
  core/src/main/java/tc/oc/pgm/flag/FlagModule.java
  core/src/main/java/tc/oc/pgm/flag/FlagParser.java
  core/src/main/java/tc/oc/pgm/flag/NetDefinition.java
  core/src/main/java/tc/oc/pgm/flag/Post.java
  core/src/main/java/tc/oc/pgm/flag/event/FlagCaptureEvent.java
  core/src/main/java/tc/oc/pgm/flag/post/CompositePost.java
  core/src/main/java/tc/oc/pgm/flag/post/PostDefinition.java
  core/src/main/java/tc/oc/pgm/flag/post/PostResolver.java
  core/src/main/java/tc/oc/pgm/flag/post/RandomOrderPostResolver.java
  core/src/main/java/tc/oc/pgm/flag/post/SequentialPostResolver.java
  core/src/main/java/tc/oc/pgm/flag/post/SinglePost.java
  core/src/main/java/tc/oc/pgm/flag/state/BaseState.java
  core/src/main/java/tc/oc/pgm/flag/state/Captured.java
  core/src/main/java/tc/oc/pgm/flag/state/Carried.java
  core/src/main/java/tc/oc/pgm/flag/state/Respawning.java
  core/src/main/java/tc/oc/pgm/flag/state/State.java
Labels: feature

#994 Fix banner placement exception breaking flags
  core/src/main/java/tc/oc/pgm/flag/state/Uncarried.java
  util/src/main/java/tc/oc/pgm/util/material/Materials.java
Labels: bug
