Repository PGMDev/PGM, pull requests merged in 2022-07, with the labels that each got.

#950 Introduce Monostable filters
  core/src/main/java/tc/oc/pgm/api/filter/Filter.java
  core/src/main/java/tc/oc/pgm/api/filter/ReactorFactory.java
  core/src/main/java/tc/oc/pgm/api/filter/query/MatchQuery.java
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  core/src/main/java/tc/oc/pgm/filters/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/FilterModule.java
  core/src/main/java/tc/oc/pgm/filters/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/LegacyFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/MonostableFilter.java
  core/src/main/java/tc/oc/pgm/filters/MultiFilterFunction.java
  core/src/main/java/tc/oc/pgm/filters/ParentFilter.java
  core/src/main/java/tc/oc/pgm/filters/SingleFilterFunction.java
  core/src/main/java/tc/oc/pgm/filters/TimeFilter.java
  core/src/main/java/tc/oc/pgm/filters/dynamic/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/filters/dynamic/Filterables.java
  core/src/main/java/tc/oc/pgm/filters/modifier/QueryModifier.java
  core/src/main/java/tc/oc/pgm/worldborder/WorldBorderModule.java
  util/src/main/java/tc/oc/pgm/util/collection/ContextStore.java
Labels: ready

#1016 Implement actions and triggers!
  core/src/main/java/tc/oc/pgm/action/Action.java
  core/src/main/java/tc/oc/pgm/action/ActionDefinition.java
  core/src/main/java/tc/oc/pgm/action/ActionMatchModule.java
  core/src/main/java/tc/oc/pgm/action/ActionModule.java
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/Trigger.java
  core/src/main/java/tc/oc/pgm/action/XMLActionReference.java
  core/src/main/java/tc/oc/pgm/action/actions/AbstractAction.java
  core/src/main/java/tc/oc/pgm/action/actions/ActionNode.java
  core/src/main/java/tc/oc/pgm/action/actions/ChatMessageAction.java
  core/src/main/java/tc/oc/pgm/action/actions/ScopeSwitchAction.java
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/features/XMLFeatureReference.java
  core/src/main/java/tc/oc/pgm/kits/ActionKit.java
  core/src/main/java/tc/oc/pgm/kits/Kit.java
  core/src/main/java/tc/oc/pgm/kits/KitDefinition.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
Labels: ready

#1031 Fix up broken action xml parsing
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
Labels: urgent

#1035 Fix missing dependency on jar
  core/pom.xml
Labels: bug, urgent
