Repository PGMDev/PGM, pull requests merged in 2023-03, with the labels that each got.

#1147 Tweak tablist rate limit on cycle
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  util/src/main/java/tc/oc/pgm/util/concurrent/RateLimiter.java
Labels: urgent

#1149 Implement pulse filter
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/PulseFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
Labels: feature

#1155 Remove EntityLaunchEvent from carrying event list
  core/src/main/java/tc/oc/pgm/filters/matcher/player/CarryingItemFilter.java
Labels: bug, urgent

#1152 Fix blitz allowing join & wrongly dropping items
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
  core/src/main/java/tc/oc/pgm/teams/TeamMatchModule.java
Labels: bug, urgent

#1156 Fix minor dynamic filter issues
  core/src/main/java/tc/oc/pgm/api/filter/query/MatchQuery.java
  core/src/main/java/tc/oc/pgm/api/filter/query/PlayerQuery.java
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/CarryingFlagFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/ParticipantFilter.java
  core/src/main/java/tc/oc/pgm/regions/RegionMatchModule.java
Labels: bug

#1159 Fix respawn filter parsing being stateful
  core/src/main/java/tc/oc/pgm/spawns/SpawnModule.java
Labels: bug, urgent

#1163 Fix up include reloading when files change
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/api/map/MapSource.java
  core/src/main/java/tc/oc/pgm/api/map/includes/MapInclude.java
  core/src/main/java/tc/oc/pgm/api/map/includes/MapIncludeProcessor.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeImpl.java
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeProcessorImpl.java
  core/src/main/java/tc/oc/pgm/map/source/SystemMapSourceFactory.java
Labels: bug, ready

#1162 Enforce validation of dynamic filter type for triggers
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/DynamicFilterValidation.java
Labels: bug, ready

#1161 Default to new map when same version number is used
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
Labels: bug, ready

#1150 Add custom firework designs 🎆
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature, ready
