Repository PGMDev/PGM, pull requests merged in 2023-10, with the labels that each got.

#1249 Add max and min to expressions
  util/src/main/java/tc/oc/pgm/util/math/Formula.java
Labels: ready

#1247 Add team scale command & add admin chat feedback for other commands
  core/src/main/java/tc/oc/pgm/command/CancelCommand.java
  core/src/main/java/tc/oc/pgm/command/FreeForAllCommand.java
  core/src/main/java/tc/oc/pgm/command/StartCommand.java
  core/src/main/java/tc/oc/pgm/command/TeamCommand.java
  core/src/main/java/tc/oc/pgm/command/TimeLimitCommand.java
  util/src/main/i18n/templates/join.properties
  util/src/main/i18n/templates/match.properties
Labels: ready

#1251 Improve killrewards, support action & victim action
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/killreward/KillReward.java
  core/src/main/java/tc/oc/pgm/killreward/KillRewardMatchModule.java
  core/src/main/java/tc/oc/pgm/killreward/KillRewardModule.java
  core/src/main/java/tc/oc/pgm/kits/KitNode.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
Labels: ready

#1255 Fix NPE on inventory view & modernize code
  core/src/main/java/tc/oc/pgm/inventory/ViewInventoryMatchModule.java
Labels: bug

#1264 fix(DeathMessageBuilder): check for null potion effect
  core/src/main/java/tc/oc/pgm/death/DeathMessageBuilder.java
Labels: bug, ready

#1261 Cleanup material filter & matcher legacy usages
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
  core/src/main/java/tc/oc/pgm/core/Core.java
  core/src/main/java/tc/oc/pgm/destroyable/Destroyable.java
  core/src/main/java/tc/oc/pgm/filters/matcher/block/BlockFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/block/MaterialFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/damage/AttackerQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/matcher/damage/VictimQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/modifier/LocationQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/modifier/PlayerBlockQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/modifier/PlayerQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/modifier/QueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/modifier/SameTeamQueryModifier.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/LegacyFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/query/BlockQuery.java
  core/src/main/java/tc/oc/pgm/filters/query/MaterialQuery.java
  core/src/main/java/tc/oc/pgm/modules/ItemDestroyMatchModule.java
  core/src/main/java/tc/oc/pgm/modules/ItemDestroyModule.java
  core/src/main/java/tc/oc/pgm/modules/ItemKeepMatchModule.java
  core/src/main/java/tc/oc/pgm/modules/ItemKeepModule.java
  core/src/main/java/tc/oc/pgm/regions/FiniteBlockRegion.java
  util/src/main/java/tc/oc/pgm/util/material/MaterialMatcher.java
  util/src/main/java/tc/oc/pgm/util/material/matcher/AllMaterialMatcher.java
  util/src/main/java/tc/oc/pgm/util/material/matcher/BlockMaterialMatcher.java
  util/src/main/java/tc/oc/pgm/util/material/matcher/CompoundMaterialMatcher.java
  util/src/main/java/tc/oc/pgm/util/material/matcher/NoMaterialMatcher.java
  util/src/main/java/tc/oc/pgm/util/material/matcher/SingleMaterialMatcher.java
Labels: refactor, ready

#1265 Implement support for variable controlled buildheight
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  core/src/main/java/tc/oc/pgm/filters/matcher/block/MaxBuildFilter.java
  core/src/main/java/tc/oc/pgm/filters/operator/AllowFilter.java
  core/src/main/java/tc/oc/pgm/filters/operator/DenyFilter.java
  core/src/main/java/tc/oc/pgm/portals/PortalModule.java
  core/src/main/java/tc/oc/pgm/regions/RFAContext.java
  core/src/main/java/tc/oc/pgm/regions/RegionFilterApplicationParser.java
  core/src/main/java/tc/oc/pgm/regions/RegionMatchModule.java
  core/src/main/java/tc/oc/pgm/regions/RegionModule.java
  core/src/main/java/tc/oc/pgm/tnt/TNTModule.java
  core/src/main/java/tc/oc/pgm/variables/VariableParser.java
  core/src/main/java/tc/oc/pgm/variables/types/MaxBuildVariable.java
Labels: feature, ready

#1263 Fix duplicate inline filter references not working
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
Labels: feature, ready

#1266 Update cloud & add variable set command
  core/pom.xml
  core/src/main/java/tc/oc/pgm/command/MapDevCommand.java
  core/src/main/java/tc/oc/pgm/command/ModeCommand.java
  core/src/main/java/tc/oc/pgm/command/parsers/MatchObjectParser.java
  core/src/main/java/tc/oc/pgm/command/parsers/VariableParser.java
  core/src/main/java/tc/oc/pgm/command/util/PGMCommandGraph.java
  core/src/main/java/tc/oc/pgm/variables/VariablesMatchModule.java
  pom.xml
Labels: feature
