Repository PGMDev/PGM, pull requests merged in 2023-07, with the labels that each got.

#1187 Refactor NMSHacks to make multi-version support easier
  core/src/main/java/tc/oc/pgm/action/actions/FillAction.java
  core/src/main/java/tc/oc/pgm/api/event/BlockTransformEvent.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/blockdrops/BlockDropsMatchModule.java
  core/src/main/java/tc/oc/pgm/blockdrops/BlockDropsRuleSet.java
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
  core/src/main/java/tc/oc/pgm/flag/LegacyFlagBeamMatchModule.java
  core/src/main/java/tc/oc/pgm/inventory/ViewInventoryMatchModule.java
  core/src/main/java/tc/oc/pgm/listeners/BlockTransformListener.java
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
  core/src/main/java/tc/oc/pgm/match/MatchFactoryImpl.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/portals/PortalTransform.java
  core/src/main/java/tc/oc/pgm/renewable/Renewable.java
  core/src/main/java/tc/oc/pgm/snapshot/BudgetWorldEdit.java
  core/src/main/java/tc/oc/pgm/snapshot/WorldSnapshot.java
  core/src/main/java/tc/oc/pgm/spawner/objects/SpawnablePotion.java
  core/src/main/java/tc/oc/pgm/tnt/TNTMatchModule.java
  core/src/main/java/tc/oc/pgm/tntrender/TNTRenderMatchModule.java
  util/src/main/java/tc/oc/pgm/util/block/BlockStates.java
  util/src/main/java/tc/oc/pgm/util/concurrent/RateLimiter.java
  util/src/main/java/tc/oc/pgm/util/inventory/InventoryUtils.java
  util/src/main/java/tc/oc/pgm/util/nms/EnumPlayerInfoAction.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacksNoOp.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacksPlatform.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacksSportPaper.java
  util/src/main/java/tc/oc/pgm/util/nms/attribute/AttributeInstance1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/attribute/AttributeMap1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/attribute/AttributeMapNoOp.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/fake/FakeEntity.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/fake/FakeEntityImpl1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/fake/FakeEntityNoOp.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/fake/FakeLivingEntity1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/fake/armorstand/FakeArmorStand1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/fake/wither/FakeWitherSkull1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/potion/EntityPotion.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/potion/EntityPotion1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/entity/potion/EntityPotionBukkit.java
  util/src/main/java/tc/oc/pgm/util/reflect/MinecraftReflectionUtils.java
  util/src/main/java/tc/oc/pgm/util/reflect/ReflectionUtils.java
  util/src/main/java/tc/oc/pgm/util/tablist/PlayerTabEntry.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabDisplay.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabRender.java
Labels: refactor

#1207 Fix potion spawners
  util/src/main/java/tc/oc/pgm/util/nms/entity/potion/EntityPotion1_8.java
Labels: bug, urgent

#1203 Allow username tabbing in channel messages
  core/src/main/java/tc/oc/pgm/command/util/PGMCommandGraph.java
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  core/src/main/java/tc/oc/pgm/util/Players.java
Labels: ready
