Repository PGMDev/PGM, pull requests merged in 2023-02, with the labels that each got.

#1120 Fix index out of bounds exception on velocity attribute parsing
  core/src/main/java/tc/oc/pgm/regions/RegionFilterApplicationParser.java
Labels: bug

#1122 Fix new settings
  core/src/main/java/tc/oc/pgm/api/setting/SettingKey.java
Labels: bug

#1121 Fix proximity alarms
  core/src/main/java/tc/oc/pgm/controlpoint/RegionPlayerTracker.java
  core/src/main/java/tc/oc/pgm/proximity/ProximityAlarm.java
  core/src/main/java/tc/oc/pgm/proximity/ProximityAlarmMatchModule.java
Labels: bug

#1119 Only check .xml files in the map includes directory
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeProcessorImpl.java
Labels: bug

#1125 Fix friend death message broadcasts
  core/src/main/java/tc/oc/pgm/death/DeathMessageMatchModule.java
Labels: bug

#1124 Fix tablist order for friends and nicked players
  core/src/main/java/tc/oc/pgm/tablist/PlayerOrder.java
Labels: bug

#1118 Implement scoreboard filters
  core/src/main/java/tc/oc/pgm/blitz/BlitzConfig.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzModule.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
  core/src/main/java/tc/oc/pgm/core/CoreModule.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableModule.java
  core/src/main/java/tc/oc/pgm/flag/FlagParser.java
  core/src/main/java/tc/oc/pgm/goals/Goal.java
  core/src/main/java/tc/oc/pgm/goals/ShowOptions.java
  core/src/main/java/tc/oc/pgm/goals/SimpleGoal.java
  core/src/main/java/tc/oc/pgm/score/ScoreConfig.java
  core/src/main/java/tc/oc/pgm/score/ScoreMatchModule.java
  core/src/main/java/tc/oc/pgm/score/ScoreModule.java
  core/src/main/java/tc/oc/pgm/scoreboard/RenderContext.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarRenderer.java
  core/src/main/java/tc/oc/pgm/wool/WoolModule.java
Labels: feature, ready

#1128 Prevent /reply revealing vanished players
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  util/src/main/i18n/templates/command.properties
Labels: bug

#1134 Fix friend only settings for observers and messages
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
Labels: bug

#1131 Add consumables
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumableDefinition.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumableMatchModule.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumableModule.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumeCause.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/kits/tag/ItemTags.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileMatchModule.java
  util/src/main/java/tc/oc/pgm/util/inventory/InventoryUtils.java
Labels: feature, ready

#1126 Fix vanish state and tablist
  core/src/main/java/tc/oc/pgm/api/player/MatchPlayer.java
  core/src/main/java/tc/oc/pgm/api/player/event/PlayerVanishEvent.java
  core/src/main/java/tc/oc/pgm/command/MatchCommand.java
  core/src/main/java/tc/oc/pgm/integrations/SimpleVanishIntegration.java
  core/src/main/java/tc/oc/pgm/join/JoinMatchModule.java
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
  core/src/main/java/tc/oc/pgm/teams/TeamMatchModule.java
  core/src/main/java/tc/oc/pgm/util/player/PlayerData.java
  util/src/main/java/tc/oc/pgm/util/tablist/PlayerTabEntry.java
Labels: bug

#1136 Refactor join logic & add support for squads
  core/src/main/java/tc/oc/pgm/api/integration/Integration.java
  core/src/main/java/tc/oc/pgm/api/integration/SquadIntegration.java
  core/src/main/java/tc/oc/pgm/api/match/Match.java
  core/src/main/java/tc/oc/pgm/api/match/event/MatchAfterLoadEvent.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/command/MapCommand.java
  core/src/main/java/tc/oc/pgm/command/TeamCommand.java
  core/src/main/java/tc/oc/pgm/command/parsers/OfflinePlayerParser.java
  core/src/main/java/tc/oc/pgm/command/util/PGMCommandGraph.java
  core/src/main/java/tc/oc/pgm/doublejump/DoubleJumpMatchModule.java
  core/src/main/java/tc/oc/pgm/events/PlayerJoinMatchEvent.java
  core/src/main/java/tc/oc/pgm/events/PlayerJoinPartyEvent.java
  core/src/main/java/tc/oc/pgm/events/PlayerParticipationStartEvent.java
  core/src/main/java/tc/oc/pgm/events/PlayerPartyChangeEvent.java
  core/src/main/java/tc/oc/pgm/ffa/FreeForAllMatchModule.java
  core/src/main/java/tc/oc/pgm/join/GenericJoinResult.java
  core/src/main/java/tc/oc/pgm/join/JoinGuard.java
  core/src/main/java/tc/oc/pgm/join/JoinHandler.java
  core/src/main/java/tc/oc/pgm/join/JoinMatchModule.java
  core/src/main/java/tc/oc/pgm/join/JoinRequest.java
  core/src/main/java/tc/oc/pgm/join/JoinResult.java
  core/src/main/java/tc/oc/pgm/join/JoinResultOption.java
  core/src/main/java/tc/oc/pgm/kits/TeamSwitchKit.java
  core/src/main/java/tc/oc/pgm/match/MatchFactoryImpl.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/match/QueuedParty.java
  core/src/main/java/tc/oc/pgm/picker/PickerMatchModule.java
  core/src/main/java/tc/oc/pgm/spawner/Spawner.java
  core/src/main/java/tc/oc/pgm/start/StartMatchModule.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
  core/src/main/java/tc/oc/pgm/tablist/PlayerOrder.java
  core/src/main/java/tc/oc/pgm/teams/Team.java
  core/src/main/java/tc/oc/pgm/teams/TeamMatchModule.java
  core/src/main/java/tc/oc/pgm/util/PrettyPaginatedComponentResults.java
  core/src/main/java/tc/oc/pgm/util/player/PlayerRelationship.java
  core/src/main/java/tc/oc/pgm/util/player/PlayerRenderer.java
  util/src/main/java/tc/oc/pgm/util/concurrent/RateLimiter.java
  util/src/main/java/tc/oc/pgm/util/named/NameStyle.java
  util/src/main/java/tc/oc/pgm/util/text/TextFormatter.java
Labels: refactor

#1141 Re-add methods to avoid 3rd party plugin breakage
  core/src/main/java/tc/oc/pgm/teams/Team.java
Labels: urgent

#1142 Fix book creator never being overriden
  core/src/main/java/tc/oc/pgm/rotation/vote/MapPoll.java
Labels: bug

#1144 Fix interaction NPE when player not in match
  core/src/main/java/tc/oc/pgm/regions/RegionMatchModule.java
Labels: bug

#1138 Add arrow pickup prevention
  core/src/main/java/tc/oc/pgm/modules/ModifyBowProjectileMatchModule.java
  core/src/main/java/tc/oc/pgm/modules/ModifyBowProjectileModule.java
Labels: feature, ready

#1145 Tablist rendering performance & responsiveness improvements
  core/src/main/java/tc/oc/pgm/integrations/SimpleVanishIntegration.java
  core/src/main/java/tc/oc/pgm/listeners/PGMListener.java
  core/src/main/java/tc/oc/pgm/match/MatchFactoryImpl.java
  core/src/main/java/tc/oc/pgm/modules/MapmakerMatchModule.java
  core/src/main/java/tc/oc/pgm/namedecorations/NameDecorationRegistryImpl.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarMatchModule.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
  core/src/main/java/tc/oc/pgm/tablist/MatchTabView.java
  core/src/main/java/tc/oc/pgm/util/player/PlayerComponent.java
  core/src/main/java/tc/oc/pgm/util/player/PlayerRenderer.java
  core/src/main/java/tc/oc/pgm/worldborder/WorldBorderMatchModule.java
  util/src/main/java/tc/oc/pgm/util/concurrent/RateLimiter.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabManager.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabManagerDirtyTracker.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
  util/src/main/java/tc/oc/pgm/util/tablist/TabViewDirtyTracker.java
Labels: bug, refactor
