Repository PGMDev/PGM, pull requests merged in 2023-11, with the labels that each got.

#1270 Fix mode commands unwanted syntax
  core/pom.xml
  core/src/main/java/tc/oc/pgm/command/ModeCommand.java
Labels: bug, urgent

#1271 Fix shading of exp4j
  core/pom.xml
Labels: urgent

#1274 Implement array variable type
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/SetVariableAction.java
  core/src/main/java/tc/oc/pgm/command/MapDevCommand.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/VariableFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/party/TeamVariableFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/rotation/vote/MapVotePicker.java
  core/src/main/java/tc/oc/pgm/variables/Variable.java
  core/src/main/java/tc/oc/pgm/variables/VariableContextBuilder.java
  core/src/main/java/tc/oc/pgm/variables/VariableDefinition.java
  core/src/main/java/tc/oc/pgm/variables/VariableParser.java
  core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
  core/src/main/java/tc/oc/pgm/variables/types/ArrayVariable.java
  core/src/main/java/tc/oc/pgm/variables/types/IndexedVariable.java
  core/src/main/java/tc/oc/pgm/variables/types/TeamVariableAdapter.java
  pom.xml
  util/src/main/java/tc/oc/pgm/util/math/Formula.java
  util/src/main/java/tc/oc/pgm/util/math/VariableExpressionContext.java
Labels: ready

#1278 Fix max build variable dependencies
  core/src/main/java/tc/oc/pgm/api/module/ModuleGraph.java
  core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
Labels: bug, urgent
