Repository PGMDev/PGM, pull requests merged in 2023-06, with the labels that each got.

#1192 Fix BlockDrop item velocity not matching vanilla block drop velocity
  core/src/main/java/tc/oc/pgm/blockdrops/BlockDropsMatchModule.java
Labels: bug

#1193 Fix maps from git repos not being updated
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
Labels: bug

#1194 Implement order & display-all capability for pool command
  core/src/main/java/tc/oc/pgm/command/MapPoolCommand.java
Labels: feature

#1197 Fix compile error on newer jdks & cleanup
  core/src/main/java/tc/oc/pgm/api/map/factory/MapSourceFactory.java
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
  core/src/main/java/tc/oc/pgm/map/source/GitMapSourceFactory.java
  core/src/main/java/tc/oc/pgm/map/source/PathMapSourceFactory.java
  core/src/main/java/tc/oc/pgm/map/source/StreamMapSourceFactory.java
Labels: bug, urgent
