Repository PGMDev/PGM, pull requests merged in 2023-04, with the labels that each got.

#1165 Avoid null filterables being added to dirty set
  core/src/main/java/tc/oc/pgm/filters/FilterMatchModule.java
Labels: bug, urgent

#1044 Lootables
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/api/filter/query/BlockQuery.java
  core/src/main/java/tc/oc/pgm/api/filter/query/EntityQuery.java
  core/src/main/java/tc/oc/pgm/api/filter/query/InventoryQuery.java
  core/src/main/java/tc/oc/pgm/api/filter/query/PlayerQuery.java
  core/src/main/java/tc/oc/pgm/api/match/Match.java
  core/src/main/java/tc/oc/pgm/filters/query/BlockQuery.java
  core/src/main/java/tc/oc/pgm/filters/query/EntityQuery.java
  core/src/main/java/tc/oc/pgm/filters/query/PlayerQuery.java
  core/src/main/java/tc/oc/pgm/filters/query/PlayerStateQuery.java
  core/src/main/java/tc/oc/pgm/itemmeta/ItemModifyMatchModule.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/kits/Slot.java
  core/src/main/java/tc/oc/pgm/loot/Cache.java
  core/src/main/java/tc/oc/pgm/loot/FillerDefinition.java
  core/src/main/java/tc/oc/pgm/loot/Loot.java
  core/src/main/java/tc/oc/pgm/loot/LootParser.java
  core/src/main/java/tc/oc/pgm/loot/LootableMatchModule.java
  core/src/main/java/tc/oc/pgm/loot/LootableModule.java
  core/src/main/java/tc/oc/pgm/loot/WeightedRandomChooser.java
  core/src/main/java/tc/oc/pgm/loot/WorldTickClock.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/regions/XMLRegionReference.java
  core/src/main/java/tc/oc/pgm/util/compose/All.java
  core/src/main/java/tc/oc/pgm/util/compose/Any.java
  core/src/main/java/tc/oc/pgm/util/compose/Composition.java
  core/src/main/java/tc/oc/pgm/util/compose/CompositionParser.java
  core/src/main/java/tc/oc/pgm/util/compose/Maybe.java
  core/src/main/java/tc/oc/pgm/util/compose/None.java
  core/src/main/java/tc/oc/pgm/util/compose/Unit.java
  util/src/main/java/tc/oc/pgm/util/Pair.java
  util/src/main/java/tc/oc/pgm/util/collection/DefaultMapAdapter.java
  util/src/main/java/tc/oc/pgm/util/collection/InstantMap.java
  util/src/main/java/tc/oc/pgm/util/range/Ranges.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
  util/src/test/java/tc/oc/pgm/util/xml/ParseRangeTest.java
Labels: feature, reintroduce

#1091 Make Gamemode name strings non-translatable
  core/src/main/java/tc/oc/pgm/api/map/Gamemode.java
  core/src/main/java/tc/oc/pgm/api/map/MapTag.java
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointModule.java
  core/src/main/java/tc/oc/pgm/scoreboard/SidebarRenderer.java
  util/src/main/i18n/templates/gamemode.properties
Labels: feature, discussion

#1170 Fix potential atomicity issue for team tags
  core/src/main/java/tc/oc/pgm/teams/TeamModule.java
Labels: bug

#1171 Support fast respawns & fix blitz bugged dead state
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/spawns/RespawnOptions.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnMatchModule.java
  core/src/main/java/tc/oc/pgm/spawns/SpawnModule.java
  core/src/main/java/tc/oc/pgm/spawns/states/Dead.java
Labels: feature

#1106 Implement PoC inline filters
  core/src/main/java/tc/oc/pgm/features/FeatureDefinitionContext.java
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature, discussion, ready

#1095 Multiple winner support in FFA tie
  core/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java
  util/src/main/i18n/templates/match.properties
Labels: reintroduce

#1175 Fix prevented team force due to combatlog & improve api
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/events/PlayerParticipationEvent.java
  core/src/main/java/tc/oc/pgm/events/PlayerParticipationStartEvent.java
  core/src/main/java/tc/oc/pgm/events/PlayerParticipationStopEvent.java
  core/src/main/java/tc/oc/pgm/filters/Filterable.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/tracker/trackers/CombatLogTracker.java
Labels: bug

#1148 Remove unused string and add context in moderation.properties
  util/src/main/i18n/templates/moderation.properties
Labels: docs, ready
