Repository PGMDev/PGM, pull requests merged in 2023-09, with the labels that each got.

#1229 Fix structures having improper locations in some instances
  core/src/main/java/tc/oc/pgm/structure/DynamicStructureDefinition.java
  core/src/main/java/tc/oc/pgm/structure/StructureDefinition.java
Labels: bug

#1231 Fix relative path repos not loading any maps
  core/src/main/java/tc/oc/pgm/map/source/MapRoot.java
Labels: bug, urgent

#1234 Add id to arbitrary dom exceptions
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/map/MapFilePreprocessor.java
  core/src/main/java/tc/oc/pgm/map/source/SystemMapSource.java
  util/src/main/java/tc/oc/pgm/util/xml/InvalidXMLException.java
Labels: bug

#1235 Fix 1.9 issues with bedwars maps
  core/src/main/java/tc/oc/pgm/shops/ShopKeeper.java
  core/src/main/java/tc/oc/pgm/shops/menu/Payment.java
  core/src/main/java/tc/oc/pgm/util/MethodHandleUtils.java
  util/src/main/java/tc/oc/pgm/util/inventory/ItemMatcher.java
  util/src/main/java/tc/oc/pgm/util/material/Materials.java
Labels: bug

#1236 Fix leave messages sometimes showing for vanished players
  core/src/main/java/tc/oc/pgm/integrations/SimpleVanishIntegration.java
Labels: bug

#1237 Add power attribute for projectiles
  core/src/main/java/tc/oc/pgm/projectile/ProjectileDefinition.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileMatchModule.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileModule.java
Labels: feature

#1238 Fix carrying and holding filters not detecting some inventory changes
  core/src/main/java/tc/oc/pgm/filters/matcher/player/CarryingItemFilter.java
  core/src/main/java/tc/oc/pgm/filters/matcher/player/HoldingItemFilter.java
Labels: bug
