Repository PGMDev/PGM, pull requests merged in 2023-08, with the labels that each got.

#1212 Update dependencies and use non-deprecated methods
  core/src/main/java/tc/oc/pgm/flag/state/Carried.java
  core/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java
  core/src/main/java/tc/oc/pgm/spawns/states/Spawning.java
  pom.xml
Labels: ready

#1177 refactor holograms out of flags
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/flag/Flag.java
  core/src/main/java/tc/oc/pgm/flag/FlagModule.java
  core/src/main/java/tc/oc/pgm/flag/state/BaseState.java
  core/src/main/java/tc/oc/pgm/flag/state/Dropped.java
  core/src/main/java/tc/oc/pgm/flag/state/Uncarried.java
  core/src/main/java/tc/oc/pgm/hologram/Hologram.java
  core/src/main/java/tc/oc/pgm/hologram/HologramMatchModule.java
  util/src/main/java/tc/oc/pgm/util/Assert.java
Labels: ready

#1208 Add per team player stats with extra trackers
  core/src/main/java/tc/oc/pgm/goals/GoalMatchModule.java
  core/src/main/java/tc/oc/pgm/stats/PlayerStats.java
  core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
  core/src/main/java/tc/oc/pgm/stats/TeamStats.java
  core/src/main/java/tc/oc/pgm/stats/menu/items/PlayerStatsMenuItem.java
  core/src/main/java/tc/oc/pgm/stats/menu/items/TeamStatsMenuItem.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: ready

#1214 Add support for variables acting on Blitz Lives
  core/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java
  core/src/main/java/tc/oc/pgm/blitz/LifeManager.java
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/variables/BlitzVariable.java
  core/src/main/java/tc/oc/pgm/variables/DummyVariable.java
  core/src/main/java/tc/oc/pgm/variables/Variable.java
  core/src/main/java/tc/oc/pgm/variables/VariableDefinition.java
  core/src/main/java/tc/oc/pgm/variables/VariableType.java
  core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
Labels: ready

#1218 Add a play-sound action
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/SoundType.java
  core/src/main/java/tc/oc/pgm/action/actions/SoundAction.java
Labels: ready

#1221 Add unused xml detection
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/map/MapFilePreprocessor.java
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeImpl.java
  core/src/main/java/tc/oc/pgm/map/includes/MapIncludeProcessorImpl.java
  core/src/main/resources/config.yml
  util/src/main/java/tc/oc/pgm/util/bukkit/Platform.java
  util/src/main/java/tc/oc/pgm/util/xml/DocumentWrapper.java
  util/src/main/java/tc/oc/pgm/util/xml/InheritingElement.java
  util/src/main/java/tc/oc/pgm/util/xml/InvalidXMLException.java
  util/src/main/java/tc/oc/pgm/util/xml/Node.java
  util/src/main/java/tc/oc/pgm/util/xml/SAXHandler.java
  util/src/main/java/tc/oc/pgm/util/xml/VisitableAttribute.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
  util/src/test/java/tc/oc/pgm/util/xml/ParseRangeTest.java
Labels: ready

#1222 Workarround adventure breaking translatable comments
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  util/src/main/java/tc/oc/pgm/util/bukkit/ViaUtils.java
Labels: bug, ready

#1220 Add Score & team-rescoping variables
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/broadcast/BroadcastModule.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumableModule.java
  core/src/main/java/tc/oc/pgm/controlpoint/ControlPointParser.java
  core/src/main/java/tc/oc/pgm/enderchest/EnderChestModule.java
  core/src/main/java/tc/oc/pgm/filters/matcher/match/VariableFilter.java
  core/src/main/java/tc/oc/pgm/filters/parse/FeatureFilterParser.java
  core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java
  core/src/main/java/tc/oc/pgm/goals/ProximityMetric.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/map/MapInfoImpl.java
  core/src/main/java/tc/oc/pgm/map/WorldInfoImpl.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileModule.java
  core/src/main/java/tc/oc/pgm/score/MercyRule.java
  core/src/main/java/tc/oc/pgm/score/ScoreMatchModule.java
  core/src/main/java/tc/oc/pgm/variables/BlitzVariable.java
  core/src/main/java/tc/oc/pgm/variables/DummyVariable.java
  core/src/main/java/tc/oc/pgm/variables/Variable.java
  core/src/main/java/tc/oc/pgm/variables/VariableDefinition.java
  core/src/main/java/tc/oc/pgm/variables/VariableParser.java
  core/src/main/java/tc/oc/pgm/variables/VariableType.java
  core/src/main/java/tc/oc/pgm/variables/VariablesMatchModule.java
  core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
  core/src/main/java/tc/oc/pgm/variables/types/AbstractVariable.java
  core/src/main/java/tc/oc/pgm/variables/types/BlitzVariable.java
  core/src/main/java/tc/oc/pgm/variables/types/DummyVariable.java
  core/src/main/java/tc/oc/pgm/variables/types/ScoreVariable.java
  core/src/main/java/tc/oc/pgm/variables/types/TeamVariableAdapter.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: urgent, ready

#1225 Add map source to /map
  core/src/main/java/tc/oc/pgm/api/map/MapSource.java
  core/src/main/java/tc/oc/pgm/command/MapCommand.java
  core/src/main/java/tc/oc/pgm/command/ShowXmlCommand.java
  core/src/main/java/tc/oc/pgm/command/util/PGMCommandGraph.java
  core/src/main/java/tc/oc/pgm/map/source/GitMapSourceFactory.java
  core/src/main/java/tc/oc/pgm/map/source/MapRoot.java
  core/src/main/java/tc/oc/pgm/map/source/PathMapSourceFactory.java
  core/src/main/java/tc/oc/pgm/map/source/SystemMapSource.java
  core/src/main/java/tc/oc/pgm/scoreboard/RenderContext.java
  util/src/main/i18n/templates/map.properties
Labels: feature, ready

#1226 Implement TNT map tag if any kit has enough tnt
  core/src/main/java/tc/oc/pgm/kits/KitModule.java
Labels: feature
