Repository PGMDev/PGM, pull requests merged in 2024-08, with the labels that each got.

#1356 Add variant support for slugs & server version limitation
  core/src/main/java/tc/oc/pgm/api/map/MapInfo.java
  core/src/main/java/tc/oc/pgm/api/map/factory/MapFactory.java
  core/src/main/java/tc/oc/pgm/command/MapCommand.java
  core/src/main/java/tc/oc/pgm/map/MapFactoryImpl.java
  core/src/main/java/tc/oc/pgm/map/MapInfoImpl.java
  core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/ModernMiscUtil.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/SpMiscUtil.java
  util/src/main/i18n/templates/command.properties
  util/src/main/java/tc/oc/pgm/util/bukkit/MiscUtils.java
  util/src/main/java/tc/oc/pgm/util/xml/DocumentWrapper.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature

#1375 Add disguise check and fix nicked user bug
  core/src/main/java/tc/oc/pgm/api/integration/Integration.java
  core/src/main/java/tc/oc/pgm/listeners/ServerPingDataListener.java
Labels: bug

#1376 Fix block data encoding in modern
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/ModernEffects.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/material/ModernBlockMaterialData.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/material/ModernEncodeUtil.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/material/ModernMaterialUtils.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/SpEffects.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/material/BlockDataIterator.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/material/SpEncodeUtil.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/material/SpMaterialData.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/material/SpMaterialUtils.java
  util/src/main/java/tc/oc/pgm/util/bukkit/Effects.java
  util/src/main/java/tc/oc/pgm/util/material/MaterialCounter.java
Labels: needs testing

#1373 Implement conditional constants
  core/src/main/java/tc/oc/pgm/map/ConditionalChecker.java
  core/src/main/java/tc/oc/pgm/map/MapFilePreprocessor.java
  util/src/main/java/tc/oc/pgm/util/Version.java
  util/src/main/java/tc/oc/pgm/util/xml/DocumentWrapper.java
Labels: feature, discussion, needs testing

#1380 Fix damage actions triggering for combustion
  core/src/main/java/tc/oc/pgm/damage/DamageMatchModule.java
Labels: bug

#1381 Fix constant attr inheritance & defined_value conditional default
  core/src/main/java/tc/oc/pgm/map/ConditionalChecker.java
  core/src/main/java/tc/oc/pgm/map/MapFilePreprocessor.java
Labels: bug

#1382 Fix player based memory leak
  core/src/main/java/tc/oc/pgm/tablist/MatchTabManager.java
Labels: bug

#1383 Fix tasks leaking after match end
  core/src/main/java/tc/oc/pgm/listeners/ChatDispatcher.java
  core/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java
  core/src/main/java/tc/oc/pgm/loot/LootableMatchModule.java
  core/src/main/java/tc/oc/pgm/loot/WorldTickClock.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  util/src/main/java/tc/oc/pgm/util/concurrent/TaskExecutorService.java
Labels: bug

#1384 Fix tab entries dirty set leaking views, players & worlds
  util/src/main/java/tc/oc/pgm/util/tablist/TabView.java
Labels: bug

#1387 Fix payload beam not being centered
  core/src/main/java/tc/oc/pgm/payload/Payload.java
Labels: bug
