Repository PGMDev/PGM, pull requests merged in 2024-03, with the labels that each got.

#1307 Do not slugify manual slugs
  core/src/main/java/tc/oc/pgm/map/MapInfoImpl.java
  util/src/main/java/tc/oc/pgm/util/StringUtils.java
Labels: bug, ready

#1288 Avoid reflection when using SportPaper
  pom.xml
  util/src/main/java/tc/oc/pgm/util/nms/v1_8/NMSHacks1_8.java
  util/src/main/java/tc/oc/pgm/util/nms/v1_8/NMSHacksSportPaper.java
Labels: ready

#1260 Add a timelimit variable
  core/src/main/java/tc/oc/pgm/timelimit/TimeLimit.java
  core/src/main/java/tc/oc/pgm/variables/VariableParser.java
  core/src/main/java/tc/oc/pgm/variables/types/TimeLimitVariable.java
Labels: feature, ready

#1292 feat: TNT minecart tracking
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/core/CoreMatchModule.java
  core/src/main/java/tc/oc/pgm/destroyable/DestroyableMatchModule.java
  core/src/main/java/tc/oc/pgm/tracker/trackers/TNTTracker.java
  util/src/main/java/tc/oc/pgm/util/listener/TNTMinecartPlacementListener.java
Labels: feature, ready
