Repository PGMDev/PGM, pull requests merged in 2024-06, with the labels that each got.

#1325 Fix illegal arg due to calculating distance between worlds
  core/pom.xml
  core/src/main/java/tc/oc/pgm/tntrender/TNTRenderMatchModule.java
  pom.xml
Labels: bug, ready

#1317 Re-add projectile trails & cleanup metadata
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/kits/tag/Grenade.java
  core/src/main/java/tc/oc/pgm/modules/ModifyBowProjectileMatchModule.java
  core/src/main/java/tc/oc/pgm/modules/ProjectileTrailMatchModule.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileMatchModule.java
  core/src/main/java/tc/oc/pgm/shops/ShopKeeper.java
  core/src/main/java/tc/oc/pgm/spawner/Spawner.java
  util/src/main/java/tc/oc/pgm/util/bukkit/MetadataUtils.java
Labels: feature, ready

#1322 Add damage history tracking and assist logic
  core/src/main/java/tc/oc/pgm/PGMConfig.java
  core/src/main/java/tc/oc/pgm/api/Config.java
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/api/player/event/MatchPlayerDeathEvent.java
  core/src/main/java/tc/oc/pgm/damagehistory/DamageEntry.java
  core/src/main/java/tc/oc/pgm/damagehistory/DamageHistory.java
  core/src/main/java/tc/oc/pgm/damagehistory/DamageHistoryKey.java
  core/src/main/java/tc/oc/pgm/damagehistory/DamageHistoryMatchModule.java
  core/src/main/java/tc/oc/pgm/kits/HealthKit.java
  core/src/main/java/tc/oc/pgm/tracker/trackers/DeathTracker.java
  core/src/main/resources/config.yml
Labels: ready

#1287 Allow for multiple game sub-elements
  core/src/main/java/tc/oc/pgm/map/MapInfoImpl.java
Labels: ready

#1308 Add Tracking Compass Module
  core/src/main/java/tc/oc/pgm/api/Modules.java
  core/src/main/java/tc/oc/pgm/compass/CompassMatchModule.java
  core/src/main/java/tc/oc/pgm/compass/CompassModule.java
  core/src/main/java/tc/oc/pgm/compass/CompassParser.java
  core/src/main/java/tc/oc/pgm/compass/CompassTarget.java
  core/src/main/java/tc/oc/pgm/compass/CompassTargetResult.java
  core/src/main/java/tc/oc/pgm/compass/OrderStrategy.java
  core/src/main/java/tc/oc/pgm/compass/targets/PlayerCompassTarget.java
  util/src/main/i18n/templates/ui.properties
Labels: feature, ready

#1327 Add a Staging phase for maps
  core/src/main/java/tc/oc/pgm/api/map/Phase.java
  util/src/main/i18n/templates/map.properties
Labels: ready

#1330 Fix up issues created with refactor
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/SpPlayerUtils.java
  pom.xml
  util/src/main/java/tc/oc/pgm/util/bukkit/PotionEffects.java
Labels: bug, urgent

#1333 Improve compass tracking module
  core/src/main/java/tc/oc/pgm/compass/CompassMatchModule.java
  core/src/main/java/tc/oc/pgm/compass/CompassModule.java
  core/src/main/java/tc/oc/pgm/compass/CompassParser.java
  core/src/main/java/tc/oc/pgm/compass/CompassTarget.java
  core/src/main/java/tc/oc/pgm/compass/CompassTargetResult.java
  core/src/main/java/tc/oc/pgm/compass/targets/FlagCompassTarget.java
  core/src/main/java/tc/oc/pgm/compass/targets/PlayerCompassTarget.java
Labels: feature

#1335 Drop platform-specific attribute impl
  core/src/main/java/tc/oc/pgm/api/player/MatchPlayer.java
  core/src/main/java/tc/oc/pgm/inventory/ViewInventoryMatchModule.java
  core/src/main/java/tc/oc/pgm/kits/AttributeKit.java
  core/src/main/java/tc/oc/pgm/kits/KitParser.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/modules/EventFilterMatchModule.java
  core/src/main/java/tc/oc/pgm/spawns/states/Observing.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/ModernInventoryUtil.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/ModernNMSHacks.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/attribute/AttributeInstanceBukkit.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/attribute/AttributeMapBukkit.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/attribute/AttributeUtilBukkit.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/NMSHacksSportPaper.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/SpInventoryUtil.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/attribute/AttributeUtilBukkit.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/attribute/SpAttributeInstance.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/attribute/SpAttributeMap.java
  util/src/main/java/tc/oc/pgm/util/StringUtils.java
  util/src/main/java/tc/oc/pgm/util/attribute/Attribute.java
  util/src/main/java/tc/oc/pgm/util/attribute/AttributeInstance.java
  util/src/main/java/tc/oc/pgm/util/attribute/AttributeMap.java
  util/src/main/java/tc/oc/pgm/util/attribute/Attributes.java
  util/src/main/java/tc/oc/pgm/util/inventory/InventoryUtils.java
  util/src/main/java/tc/oc/pgm/util/nms/NMSHacks.java
  util/src/main/java/tc/oc/pgm/util/xml/XMLUtils.java
Labels: feature

#1339 Add PlayerJoinResultEvent
  core/src/main/java/tc/oc/pgm/events/PlayerJoinResultEvent.java
  core/src/main/java/tc/oc/pgm/join/JoinHandler.java
Labels: feature

#1341 Fix tablist layer toggling in modern
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/ModernListener.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/packets/ModernTabPackets.java
Labels: bug

#1344 Fix tnt being cancelled if player is dead
  core/src/main/java/tc/oc/pgm/api/party/Party.java
  core/src/main/java/tc/oc/pgm/api/player/MatchPlayerState.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerStateImpl.java
  core/src/main/java/tc/oc/pgm/match/ParticipantStateImpl.java
  core/src/main/java/tc/oc/pgm/match/PartyImpl.java
Labels: bug

#1345 Implement damage actions
  core/src/main/java/tc/oc/pgm/action/Action.java
  core/src/main/java/tc/oc/pgm/action/XMLActionReference.java
  core/src/main/java/tc/oc/pgm/action/actions/ActionNode.java
  core/src/main/java/tc/oc/pgm/action/actions/TakePaymentAction.java
  core/src/main/java/tc/oc/pgm/damage/DamageMatchModule.java
  core/src/main/java/tc/oc/pgm/damage/DamageModule.java
  core/src/main/java/tc/oc/pgm/filters/matcher/CauseFilter.java
Labels: feature

#1346 Add velocity action, teleport action, and related variable
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/TeleportAction.java
  core/src/main/java/tc/oc/pgm/action/actions/VelocityAction.java
  core/src/main/java/tc/oc/pgm/variables/VariableParser.java
  core/src/main/java/tc/oc/pgm/variables/types/PlayerLocationVariable.java
Labels: feature

#1348 Implement click consumables
  core/src/main/java/tc/oc/pgm/consumable/ConsumableDefinition.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumableMatchModule.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumableModule.java
  core/src/main/java/tc/oc/pgm/consumable/ConsumeCause.java
  core/src/main/java/tc/oc/pgm/projectile/ProjectileMatchModule.java
  platform/platform-modern/src/main/java/tc/oc/pgm/platform/modern/ModernInventoryUtil.java
  platform/platform-sportpaper/src/main/java/tc/oc/pgm/platform/sportpaper/SpInventoryUtil.java
  util/src/main/java/tc/oc/pgm/util/inventory/InventoryUtils.java
Labels: feature
