Repository PGMDev/PGM, pull requests merged in 2024-04, with the labels that each got.

#1309 Improve json detection for formatted text
  util/src/main/java/tc/oc/pgm/util/text/TextParser.java
Labels: bug, ready

#1305 Add take-payment action
  core/src/main/java/tc/oc/pgm/action/ActionParser.java
  core/src/main/java/tc/oc/pgm/action/actions/TakePaymentAction.java
  core/src/main/java/tc/oc/pgm/shops/Shop.java
  core/src/main/java/tc/oc/pgm/shops/ShopModule.java
  core/src/main/java/tc/oc/pgm/shops/menu/Icon.java
  core/src/main/java/tc/oc/pgm/shops/menu/Payable.java
  core/src/main/java/tc/oc/pgm/shops/menu/ShopMenu.java
Labels: feature, ready

#1304 Implement basic command flag suggestion filter
  core/src/main/java/tc/oc/pgm/command/util/CommandGraph.java
Labels: bug, ready

#1281 Update dependencies and use non-deprecated methods (take 2)
  core/src/main/java/tc/oc/pgm/flag/state/Carried.java
  core/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java
  core/src/main/java/tc/oc/pgm/spawns/states/Spawning.java
  pom.xml
Labels: ready

#1310 Optimize tnt render by ignoring afk players
  core/src/main/java/tc/oc/pgm/PGMPlugin.java
  core/src/main/java/tc/oc/pgm/api/PGM.java
  core/src/main/java/tc/oc/pgm/api/party/Party.java
  core/src/main/java/tc/oc/pgm/api/player/MatchPlayer.java
  core/src/main/java/tc/oc/pgm/goals/GoalMatchModule.java
  core/src/main/java/tc/oc/pgm/match/MatchImpl.java
  core/src/main/java/tc/oc/pgm/match/MatchPlayerImpl.java
  core/src/main/java/tc/oc/pgm/tntrender/TNTRenderMatchModule.java
  util/src/main/java/tc/oc/pgm/util/listener/AfkTracker.java
Labels: feature, ready
